/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CompetitionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Competition
        //val modelInstance = Competition()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `ageMin`
        should("test ageMin") {
            // uncomment below to test the property
            //modelInstance.ageMin shouldBe ("TODO")
        }

        // to test the property `ageMax`
        should("test ageMax") {
            // uncomment below to test the property
            //modelInstance.ageMax shouldBe ("TODO")
        }

        // to test the property `gender`
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `hasRetry`
        should("test hasRetry") {
            // uncomment below to test the property
            //modelInstance.hasRetry shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
