/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CompetitionUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompetitionUpdate
        //val modelInstance = CompetitionUpdate()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `ageMin`
        should("test ageMin") {
            // uncomment below to test the property
            //modelInstance.ageMin shouldBe ("TODO")
        }

        // to test the property `ageMax`
        should("test ageMax") {
            // uncomment below to test the property
            //modelInstance.ageMax shouldBe ("TODO")
        }

        // to test the property `gender`
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `hasRetry`
        should("test hasRetry") {
            // uncomment below to test the property
            //modelInstance.hasRetry shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
