/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CourseObstacleUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CourseObstacleUpdate
        //val modelInstance = CourseObstacleUpdate()

        // to test the property `obstacleId`
        should("test obstacleId") {
            // uncomment below to test the property
            //modelInstance.obstacleId shouldBe ("TODO")
        }

        // to test the property `position`
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

    }
}
