/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CourseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Course
        //val modelInstance = Course()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `maxDuration`
        should("test maxDuration") {
            // uncomment below to test the property
            //modelInstance.maxDuration shouldBe ("TODO")
        }

        // to test the property `position`
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

        // to test the property `isOver`
        should("test isOver") {
            // uncomment below to test the property
            //modelInstance.isOver shouldBe ("TODO")
        }

        // to test the property `competitionId`
        should("test competitionId") {
            // uncomment below to test the property
            //modelInstance.competitionId shouldBe ("TODO")
        }

    }
}
