/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CourseObstacleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CourseObstacle
        //val modelInstance = CourseObstacle()

        // to test the property `courseObstacleId`
        should("test courseObstacleId") {
            // uncomment below to test the property
            //modelInstance.courseObstacleId shouldBe ("TODO")
        }

        // to test the property `obstacleName`
        should("test obstacleName") {
            // uncomment below to test the property
            //modelInstance.obstacleName shouldBe ("TODO")
        }

        // to test the property `position`
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

    }
}
