/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class PerformanceObstacleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerformanceObstacle
        //val modelInstance = PerformanceObstacle()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `obstacleId`
        should("test obstacleId") {
            // uncomment below to test the property
            //modelInstance.obstacleId shouldBe ("TODO")
        }

        // to test the property `performanceId`
        should("test performanceId") {
            // uncomment below to test the property
            //modelInstance.performanceId shouldBe ("TODO")
        }

        // to test the property `hasFell`
        should("test hasFell") {
            // uncomment below to test the property
            //modelInstance.hasFell shouldBe ("TODO")
        }

        // to test the property `toVerify`
        should("test toVerify") {
            // uncomment below to test the property
            //modelInstance.toVerify shouldBe ("TODO")
        }

        // to test the property `time`
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
