/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class PerformanceObstacleUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerformanceObstacleUpdate
        //val modelInstance = PerformanceObstacleUpdate()

        // to test the property `hasFell`
        should("test hasFell") {
            // uncomment below to test the property
            //modelInstance.hasFell shouldBe ("TODO")
        }

        // to test the property `toVerify`
        should("test toVerify") {
            // uncomment below to test the property
            //modelInstance.toVerify shouldBe ("TODO")
        }

        // to test the property `time`
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

    }
}
