/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class PerformanceUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerformanceUpdate
        //val modelInstance = PerformanceUpdate()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `totalTime`
        should("test totalTime") {
            // uncomment below to test the property
            //modelInstance.totalTime shouldBe ("TODO")
        }

    }
}
