/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.apis

import io.kotlintest.specs.ShouldSpec

class PerformancesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PerformancesApi
        //val apiInstance = PerformancesApi()

        // to test deletePerformance
        should("test deletePerformance") {
            // uncomment below to test deletePerformance
            //val id : kotlin.Int = 56 // kotlin.Int | Performance ID in the database
            //apiInstance.deletePerformance(id)
        }

        // to test getPerformanceDetails
        should("test getPerformanceDetails") {
            // uncomment below to test getPerformanceDetails
            //val id : kotlin.Int = 56 // kotlin.Int | Performance's ID in the database
            //val result : Performance = apiInstance.getPerformanceDetails(id)
            //result shouldBe ("TODO")
        }

        // to test listPerformances
        should("test listPerformances") {
            // uncomment below to test listPerformances
            //val result : kotlin.collections.List<Performance> = apiInstance.listPerformances()
            //result shouldBe ("TODO")
        }

        // to test storePerformance
        should("test storePerformance") {
            // uncomment below to test storePerformance
            //val performanceCreate : PerformanceCreate =  // PerformanceCreate | Storing performance informations
            //apiInstance.storePerformance(performanceCreate)
        }

        // to test updatePerformance
        should("test updatePerformance") {
            // uncomment below to test updatePerformance
            //val id : kotlin.Int = 56 // kotlin.Int | Performance ID in the database
            //val performanceUpdate : PerformanceUpdate =  // PerformanceUpdate | Updating performance informations
            //apiInstance.updatePerformance(id, performanceUpdate)
        }

    }
}
