/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.clientkotlin.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param obstacleId 
 */


data class AddCourseObstacleRequest (

    @Json(name = "obstacle_id")
    val obstacleId: Int

) {


}

