/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.clientkotlin.models


import com.squareup.moshi.Json
import java.time.LocalDate

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param phone 
 * @param bornAt 
 */


data class CompetitorUpdate (

    @Json(name = "first_name")
    val firstName: String? = null,

    @Json(name = "last_name")
    val lastName: String? = null,

    @Json(name = "email")
    val email: String? = null,

    @Json(name = "phone")
    val phone: String? = null,

    @Json(name = "born_at")
    val bornAt: LocalDate? = null

) {


}

