/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.clientkotlin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable
import java.time.LocalDate
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param updatedAt 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param gender 
 * @param phone 
 * @param bornAt 
 */


data class Competitor (

    @Json(name = "id")
    val id: Int? = null,

    @Json(name = "created_at")
    val createdAt: OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: OffsetDateTime? = null,

    @Json(name = "first_name")
    val firstName: String? = null,

    @Json(name = "last_name")
    val lastName: String? = null,

    @Json(name = "email")
    val email: String? = null,

    @Json(name = "gender")
    val gender: Gender? = null,

    @Json(name = "phone")
    val phone: String? = null,

    @Json(name = "born_at")
    val bornAt: LocalDate? = null

) : Serializable{

    /**
     * 
     *
     * Values: H,F
     */
    @JsonClass(generateAdapter = false)
    enum class Gender(val value: String) {
        @Json(name = "H") H("H"),
        @Json(name = "F") F("F");
    }

}

