/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.clientkotlin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param updatedAt 
 * @param name 
 * @param ageMin 
 * @param ageMax 
 * @param gender 
 * @param hasRetry 
 * @param status 
 */


data class Competition (

    @Json(name = "id")
    val id: Int? = null,

    @Json(name = "created_at")
    val createdAt: OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: OffsetDateTime? = null,

    @Json(name = "name")
    val name: String? = null,

    @Json(name = "age_min")
    val ageMin: Int? = null,

    @Json(name = "age_max")
    val ageMax: Int? = null,

    @Json(name = "gender")
    val gender: Gender? = null,

    @Json(name = "has_retry")
    val hasRetry: Boolean? = null,

    @Json(name = "status")
    val status: Status? = null

) : Serializable {

    /**
     * 
     *
     * Values: H,F
     */
    @JsonClass(generateAdapter = false)
    enum class Gender(val value: String) : Serializable {
        @Json(name = "H") H("H"),
        @Json(name = "F") F("F");
    }
    /**
     * 
     *
     * Values: not_ready,not_started,started,finished
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: String) : Serializable {
        @Json(name = "not_ready") not_ready("not_ready"),
        @Json(name = "not_started") not_started("not_started"),
        @Json(name = "started") started("started"),
        @Json(name = "finished") finished("finished");
    }

}

