/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.clientkotlin.models


import com.squareup.moshi.Json
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param obstacleId 
 * @param performanceId 
 * @param hasFell 
 * @param toVerify 
 * @param time 
 * @param updatedAt 
 * @param createdAt 
 */


data class PerformanceObstacle (

    @Json(name = "id")
    val id: Int? = null,

    @Json(name = "obstacle_id")
    val obstacleId: Int? = null,

    @Json(name = "performance_id")
    val performanceId: Int? = null,

    @Json(name = "has_fell")
    val hasFell: Boolean? = null,

    @Json(name = "to_verify")
    val toVerify: Boolean? = null,

    @Json(name = "time")
    val time: Int? = null,

    @Json(name = "updated_at")
    val updatedAt: OffsetDateTime? = null,

    @Json(name = "created_at")
    val createdAt: OffsetDateTime? = null

) {


}

