/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.apis.genere

import io.kotlintest.specs.ShouldSpec

class CompetitionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompetitionsApi
        //val apiInstance = CompetitionsApi()

        // to test deleteCompetition
        should("test deleteCompetition") {
            // uncomment below to test deleteCompetition
            //val id : kotlin.Int = 56 // kotlin.Int | Competition ID in the database
            //apiInstance.deleteCompetition(id)
        }

        // to test getCompetitionCourses
        should("test getCompetitionCourses") {
            // uncomment below to test getCompetitionCourses
            //val id : kotlin.Int = 56 // kotlin.Int | Competition ID in the database
            //val result : kotlin.collections.List<Course> = apiInstance.getCompetitionCourses(id)
            //result shouldBe ("TODO")
        }

        // to test getCompetitionDetails
        should("test getCompetitionDetails") {
            // uncomment below to test getCompetitionDetails
            //val id : kotlin.Int = 56 // kotlin.Int | Competition ID in the database
            //val result : Competition = apiInstance.getCompetitionDetails(id)
            //result shouldBe ("TODO")
        }

        // to test getCompetitionInscriptions
        should("test getCompetitionInscriptions") {
            // uncomment below to test getCompetitionInscriptions
            //val id : kotlin.Int = 56 // kotlin.Int | Competition ID in the database
            //val result : kotlin.collections.List<Competitor> = apiInstance.getCompetitionInscriptions(id)
            //result shouldBe ("TODO")
        }

        // to test listCompetitions
        should("test listCompetitions") {
            // uncomment below to test listCompetitions
            //val result : kotlin.collections.List<Competition> = apiInstance.listCompetitions()
            //result shouldBe ("TODO")
        }

        // to test storeCompetition
        should("test storeCompetition") {
            // uncomment below to test storeCompetition
            //val competitionCreate : CompetitionCreate =  // CompetitionCreate | Competition's informations
            //val result : Competition = apiInstance.storeCompetition(competitionCreate)
            //result shouldBe ("TODO")
        }

        // to test updateCompetition
        should("test updateCompetition") {
            // uncomment below to test updateCompetition
            //val id : kotlin.Int = 56 // kotlin.Int | Competition ID in the database
            //val competitionUpdate : CompetitionUpdate =  // CompetitionUpdate | Updating competitions informations
            //apiInstance.updateCompetition(id, competitionUpdate)
        }

    }
}
