/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.but.parkour.openapitools.client.apis.genere

import io.kotlintest.specs.ShouldSpec

class UtilApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UtilApi
        //val apiInstance = UtilApi()

        // to test resetData
        should("test resetData") {
            // uncomment below to test resetData
            //apiInstance.resetData()
        }

    }
}
